### ISSUE TITLE
NppFTP crashes when connecting to an HP NonStop server

### ISSUE THREAD

**Issue by sconeu** [ashkulz/NppFTP#47]
NppFTP version 0.26.3 Unicode
zlib 1.2.8
libssh 0.6.5
Openssl 1.0.2a 19 mar 2015
![Uploading npp-crash.png…]()

**Comment by sconeu** [comment]
Corrected with proper image

![npp-crash](https://cloud.githubusercontent.com/assets/13224156/8553100/f323177c-2495-11e5-9ceb-c28e96b48d56.png)

**Comment by ashkulz** [comment]
@sconeu: are you able to reproduce this with `0.26.4` available from Github?

**Comment by gbritton1** [comment]
Same error as @sconeu with NppFTp 0.26.3 connecting to Z-OS in my case.
I cannot  find 0.26.4 anyhere

**Comment by gbritton1** [comment]
OK -- got 0.26.4 installed.  Same exact failure.

**Comment by sconeu** [comment]
I think it blows up on any non-UNIX-like file system.

**Comment by gbritton1** [comment]
Well that's really useful

On Wed, Jul 8, 2015 at 7:55 PM, sconeu <notifications@github.com> wrote:

> I think it blows up on any non-UNIX-like file system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ashkulz/NppFTP/issues/47#issuecomment-119762132>.
>



-- 
Gerald Britton
LinkedIn Profile: http://ca.linkedin.com/in/geraldbritton

**Comment by ashkulz** [comment]
Is there a public URL where I can try to reproduce?

**Comment by gbritton1** [comment]
Not sure. It failed for me on an internal site

**Comment by chcg** [comment]
@sconeu @gbritton1 Could you please retest with version v0.27.0, as some similar crashes are fixed with this release, see https://github.com/ashkulz/NppFTP/releases/tag/v0.27.0

**Comment by sconeu** [comment]
Still fails for me.  Notepad++ 7.4.1 64bit.  NppFTP 0.27.0 64bit.

**Comment by sconeu** [comment]
Follow up for chcg.   HP NonStop paths are fixed as the following regex:

$[:alpha:][:alnum:]{0,6}\.[:alnum:]{1,8}\.[:alnum:]{1,8}

Case Insensitive.

Part before the first dot is the volume name, including the leading $.
Second part (between the dots) is a subvolume name
Third part (after the second dot) is the file name.

**Comment by sconeu** [comment]
Still occurring with 0.28.3.   NPP v7.7 64 bit.

**Comment by chcg** [comment]
@sconeu See https://github.com/ashkulz/NppFTP/pull/132 regarding ussing z/OS like dir structure with . as separator. Probably this will not be supported by NppFTP, but at least it shouldn't create a crash.
